### ISSUE TITLE
Add editor to README

### ISSUE THREAD

**Issue by LagKnowsWhy** [ultimatehecker/Cybernetic#242]
**Is your feature request related to a problem? Please describe.**
I don't see vim/nvim/vi in the editor section of the bot

**Describe the solution you'd like**
Add the named editors xD

**Describe alternatives you've considered**
None...

**Comment by ultimatehecker** [comment]
just for you

**Comment by ultimatehecker** [comment]
added: https://github.com/ultimatehecker/Cybernetic/commit/0a94a52dbc077b4ab8bd78bd3677060290a6d3f3

**Comment by LagKnowsWhy** [comment]
Sick lmao
