### ISSUE TITLE
Cybernetic Defualting Welcome Message to the #rules channel

### ISSUE THREAD

**Issue by ultimatehecker** [ultimatehecker/Cybernetic#31]
When Cybernetic gets invited to another Discord Server, it send a welcome message through the `guildCreate` event, but for some reason even though it shouldn't have permissions, it automatically send it in the `#rules` channel, instead of a regular channel like `general` or `bot-commands`.

**Comment by Poly-Pixel** [comment]
The bot does have permissions :/
